language: ruby
rvm:
  - 2.6.5
before_install:
  - nvm install 6.2.0
install:
  - bundle install --jobs=3 --retry=3
  - npm install
before_script:
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake health
