development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
